services:
  db:
    image: mohistmc-db-v3-${ENV}:${VERSION}
    build:
      context: ../..
      dockerfile: Dockerfile.db
    container_name: mohistmc-db-v3-${ENV}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - mohistmc-v3-${ENV}-postgres-data:/var/lib/postgresql/data
    networks:
      - mohistmc-network-v3-${ENV}

  app:
    image: mohistmc-backend-v3-${ENV}:${VERSION}
    build:
      context: ../..
      dockerfile: Dockerfile.app
    container_name: mohistmc-backend-v3-${ENV}
    restart: always
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:postgresql://mohistmc-db-v3-${ENV}/mohistmc_website
    ports:
      - "${APP_EXTERNAL_PORT}:3568"
    volumes:
      - /var/mohistmc:/var/mohistmc
    networks:
      - mohistmc-network-v3-${ENV}

volumes:
  mohistmc-v3-${ENV}-postgres-data:

networks:
  mohistmc-network-v3-${ENV}:
    driver: bridge
    external: true