services:
  db:
    image: mohistmc-db-v3
    build:
      context: ../..
      dockerfile: Dockerfile.db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - mohistmc-v3-postgres-data:/var/lib/postgresql/data
    networks:
      - mohistmc-network-v3

  app:
    image: mohistmc-backend-v3
    build:
      context: ../..
      dockerfile: Dockerfile.app
    restart: always
    environment:
      DB_HOST: mohistmc-db-v3
      DB_NAME: mohistmc_website
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GITHUB_TOKEN: ${CREDENTIALS_GITHUB_TOKEN}
      GITHUB_USERNAME: ${CREDENTIALS_GITHUB_USERNAME}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${APP_EXTERNAL_PORT}:3568"
    volumes:
      - /var/mohistmc:/var/mohistmc
    networks:
      - mohistmc-network-v3

volumes:
  mohistmc-v3-postgres-data:

networks:
  mohistmc-network-v3:
    driver: bridge
    external: true